export interface LearningResource {
  id: string
  title: string
  type: "video" | "article" | "practice" | "tutorial" | "course" | "book" | "interactive" | "podcast"
  url: string
  difficulty: "beginner" | "intermediate" | "advanced"
  category: string
  topic: string
  description: string
  duration?: string
  readTime?: string
  provider: string
  rating: number
  tags: string[]
  prerequisites?: string[]
  language: string
  isFree: boolean
  certification?: boolean
}

// Comprehensive learning resources database
export const learningResourcesDatabase: Record<string, LearningResource[]> = {
  "computer-science": [
    // JavaScript Resources
    {
      id: "js-mdn-complete",
      title: "JavaScript Complete Guide",
      type: "tutorial",
      url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
      difficulty: "beginner",
      category: "computer-science",
      topic: "javascript",
      description: "Comprehensive JavaScript tutorial covering all fundamentals",
      readTime: "6 hours",
      provider: "MDN Web Docs",
      rating: 4.8,
      tags: ["javascript", "web-development", "fundamentals"],
      language: "English",
      isFree: true,
    },
    {
      id: "js-eloquent-book",
      title: "Eloquent JavaScript",
      type: "book",
      url: "https://eloquentjavascript.net/",
      difficulty: "intermediate",
      category: "computer-science",
      topic: "javascript",
      description: "A modern introduction to programming with JavaScript",
      readTime: "20 hours",
      provider: "Marijn Haverbeke",
      rating: 4.7,
      tags: ["javascript", "programming", "book"],
      language: "English",
      isFree: true,
    },
    {
      id: "js-freecodecamp",
      title: "JavaScript Algorithms and Data Structures",
      type: "course",
      url: "https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
      difficulty: "intermediate",
      category: "computer-science",
      topic: "javascript",
      description: "Interactive course with 300+ hours of content",
      duration: "300 hours",
      provider: "freeCodeCamp",
      rating: 4.6,
      tags: ["javascript", "algorithms", "data-structures"],
      language: "English",
      isFree: true,
      certification: true,
    },
    // Python Resources
    {
      id: "python-official-tutorial",
      title: "Python Official Tutorial",
      type: "tutorial",
      url: "https://docs.python.org/3/tutorial/",
      difficulty: "beginner",
      category: "computer-science",
      topic: "python",
      description: "Official Python tutorial from Python.org",
      readTime: "8 hours",
      provider: "Python Software Foundation",
      rating: 4.5,
      tags: ["python", "official", "tutorial"],
      language: "English",
      isFree: true,
    },
    {
      id: "python-automate-book",
      title: "Automate the Boring Stuff with Python",
      type: "book",
      url: "https://automatetheboringstuff.com/",
      difficulty: "beginner",
      category: "computer-science",
      topic: "python",
      description: "Practical programming for total beginners",
      readTime: "15 hours",
      provider: "Al Sweigart",
      rating: 4.7,
      tags: ["python", "automation", "beginner"],
      language: "English",
      isFree: true,
    },
    {
      id: "python-coursera-michigan",
      title: "Python for Everybody Specialization",
      type: "course",
      url: "https://www.coursera.org/specializations/python",
      difficulty: "beginner",
      category: "computer-science",
      topic: "python",
      description: "University of Michigan's comprehensive Python course",
      duration: "8 months",
      provider: "University of Michigan",
      rating: 4.8,
      tags: ["python", "university", "specialization"],
      language: "English",
      isFree: false,
      certification: true,
    },
    // Algorithms Resources
    {
      id: "algorithms-mit-course",
      title: "Introduction to Algorithms",
      type: "course",
      url: "https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-fall-2011/",
      difficulty: "advanced",
      category: "computer-science",
      topic: "algorithms",
      description: "MIT's comprehensive algorithms course",
      duration: "15 weeks",
      provider: "MIT OpenCourseWare",
      rating: 4.9,
      tags: ["algorithms", "data-structures", "mit"],
      prerequisites: ["basic programming"],
      language: "English",
      isFree: true,
    },
    {
      id: "algorithms-visualizer",
      title: "Algorithm Visualizer",
      type: "interactive",
      url: "https://algorithm-visualizer.org/",
      difficulty: "intermediate",
      category: "computer-science",
      topic: "algorithms",
      description: "Interactive platform for visualizing algorithms",
      provider: "Algorithm Visualizer",
      rating: 4.6,
      tags: ["algorithms", "visualization", "interactive"],
      language: "English",
      isFree: true,
    },
  ],
  health: [
    // Nutrition Resources
    {
      id: "nutrition-harvard-course",
      title: "Introduction to Nutrition",
      type: "course",
      url: "https://www.edx.org/course/introduction-to-nutrition",
      difficulty: "beginner",
      category: "health",
      topic: "nutrition",
      description: "Harvard's comprehensive nutrition science course",
      duration: "6 weeks",
      provider: "Harvard T.H. Chan School",
      rating: 4.7,
      tags: ["nutrition", "health", "harvard"],
      language: "English",
      isFree: true,
      certification: true,
    },
    {
      id: "nutrition-precision-course",
      title: "Precision Nutrition Certification",
      type: "course",
      url: "https://www.precisionnutrition.com/nutrition-certification",
      difficulty: "advanced",
      category: "health",
      topic: "nutrition",
      description: "Professional nutrition coaching certification",
      duration: "12 months",
      provider: "Precision Nutrition",
      rating: 4.8,
      tags: ["nutrition", "certification", "professional"],
      language: "English",
      isFree: false,
      certification: true,
    },
    {
      id: "nutrition-nih-resources",
      title: "NIH Nutrition Resources",
      type: "article",
      url: "https://www.niddk.nih.gov/health-information/diet-nutrition",
      difficulty: "beginner",
      category: "health",
      topic: "nutrition",
      description: "Evidence-based nutrition information from NIH",
      readTime: "2 hours",
      provider: "National Institutes of Health",
      rating: 4.6,
      tags: ["nutrition", "evidence-based", "government"],
      language: "English",
      isFree: true,
    },
    // Anatomy Resources
    {
      id: "anatomy-khan-academy",
      title: "Human Anatomy and Physiology",
      type: "video",
      url: "https://www.khanacademy.org/science/health-and-medicine/human-anatomy-and-physiology",
      difficulty: "intermediate",
      category: "health",
      topic: "anatomy",
      description: "Comprehensive video series on human body systems",
      duration: "25 hours",
      provider: "Khan Academy",
      rating: 4.8,
      tags: ["anatomy", "physiology", "video"],
      language: "English",
      isFree: true,
    },
    {
      id: "anatomy-visible-body",
      title: "Visible Body Atlas",
      type: "interactive",
      url: "https://www.visiblebody.com/",
      difficulty: "intermediate",
      category: "health",
      topic: "anatomy",
      description: "3D interactive anatomy atlas",
      provider: "Visible Body",
      rating: 4.7,
      tags: ["anatomy", "3d", "interactive"],
      language: "English",
      isFree: false,
    },
    // Mental Health Resources
    {
      id: "mental-health-coursera",
      title: "Mental Health and Wellness",
      type: "course",
      url: "https://www.coursera.org/learn/mental-health",
      difficulty: "beginner",
      category: "health",
      topic: "mental-health",
      description: "Understanding mental health and wellness strategies",
      duration: "4 weeks",
      provider: "University of California, Davis",
      rating: 4.5,
      tags: ["mental-health", "wellness", "psychology"],
      language: "English",
      isFree: true,
      certification: true,
    },
  ],
  business: [
    // Strategy Resources
    {
      id: "strategy-wharton-course",
      title: "Business Strategy Specialization",
      type: "course",
      url: "https://www.coursera.org/specializations/wharton-business-strategy",
      difficulty: "intermediate",
      category: "business",
      topic: "strategy",
      description: "Wharton's comprehensive business strategy program",
      duration: "4 months",
      provider: "University of Pennsylvania",
      rating: 4.7,
      tags: ["strategy", "wharton", "specialization"],
      language: "English",
      isFree: false,
      certification: true,
    },
    {
      id: "strategy-hbr-articles",
      title: "Harvard Business Review Strategy Collection",
      type: "article",
      url: "https://hbr.org/topic/strategy",
      difficulty: "advanced",
      category: "business",
      topic: "strategy",
      description: "Latest strategic thinking from business leaders",
      readTime: "ongoing",
      provider: "Harvard Business Review",
      rating: 4.6,
      tags: ["strategy", "harvard", "articles"],
      language: "English",
      isFree: false,
    },
    // Finance Resources
    {
      id: "finance-mit-course",
      title: "Introduction to Corporate Finance",
      type: "course",
      url: "https://ocw.mit.edu/courses/sloan-school-of-management/15-401-finance-theory-i-fall-2008/",
      difficulty: "advanced",
      category: "business",
      topic: "finance",
      description: "MIT Sloan's rigorous corporate finance course",
      duration: "12 weeks",
      provider: "MIT Sloan",
      rating: 4.8,
      tags: ["finance", "corporate", "mit"],
      prerequisites: ["basic accounting", "mathematics"],
      language: "English",
      isFree: true,
    },
    {
      id: "finance-khan-academy",
      title: "Finance and Capital Markets",
      type: "video",
      url: "https://www.khanacademy.org/economics-finance-domain/core-finance",
      difficulty: "beginner",
      category: "business",
      topic: "finance",
      description: "Comprehensive finance fundamentals",
      duration: "15 hours",
      provider: "Khan Academy",
      rating: 4.5,
      tags: ["finance", "fundamentals", "video"],
      language: "English",
      isFree: true,
    },
    // Marketing Resources
    {
      id: "marketing-google-course",
      title: "Google Digital Marketing Course",
      type: "course",
      url: "https://learndigital.withgoogle.com/digitalgarage/course/digital-marketing",
      difficulty: "beginner",
      category: "business",
      topic: "marketing",
      description: "Comprehensive digital marketing certification",
      duration: "40 hours",
      provider: "Google",
      rating: 4.4,
      tags: ["marketing", "digital", "google"],
      language: "English",
      isFree: true,
      certification: true,
    },
  ],
  law: [
    // Constitutional Law Resources
    {
      id: "constitutional-yale-course",
      title: "Constitutional Law",
      type: "course",
      url: "https://oyc.yale.edu/political-science/plsc-114",
      difficulty: "advanced",
      category: "law",
      topic: "constitutional-law",
      description: "Yale's comprehensive constitutional law course",
      duration: "16 weeks",
      provider: "Yale University",
      rating: 4.8,
      tags: ["constitutional-law", "yale", "supreme-court"],
      language: "English",
      isFree: true,
    },
    {
      id: "constitutional-justia",
      title: "Constitutional Law Resources",
      type: "article",
      url: "https://law.justia.com/constitution/",
      difficulty: "intermediate",
      category: "law",
      topic: "constitutional-law",
      description: "Free constitutional law resources and cases",
      readTime: "ongoing",
      provider: "Justia",
      rating: 4.5,
      tags: ["constitutional-law", "cases", "free"],
      language: "English",
      isFree: true,
    },
    // Contract Law Resources
    {
      id: "contracts-harvard-course",
      title: "Contract Law",
      type: "course",
      url: "https://www.edx.org/course/contract-law",
      difficulty: "intermediate",
      category: "law",
      topic: "contracts",
      description: "Harvard Law School's contract law fundamentals",
      duration: "8 weeks",
      provider: "Harvard Law School",
      rating: 4.7,
      tags: ["contracts", "harvard", "law-school"],
      language: "English",
      isFree: true,
      certification: true,
    },
  ],
  psychology: [
    // General Psychology Resources
    {
      id: "psychology-yale-intro",
      title: "Introduction to Psychology",
      type: "course",
      url: "https://oyc.yale.edu/psychology/psyc-110",
      difficulty: "beginner",
      category: "psychology",
      topic: "general-psychology",
      description: "Yale's comprehensive introduction to psychology",
      duration: "20 weeks",
      provider: "Yale University",
      rating: 4.9,
      tags: ["psychology", "yale", "introduction"],
      language: "English",
      isFree: true,
    },
    {
      id: "psychology-apa-resources",
      title: "APA Psychology Resources",
      type: "article",
      url: "https://www.apa.org/science/about/psa",
      difficulty: "intermediate",
      category: "psychology",
      topic: "general-psychology",
      description: "American Psychological Association resources",
      readTime: "ongoing",
      provider: "American Psychological Association",
      rating: 4.6,
      tags: ["psychology", "apa", "professional"],
      language: "English",
      isFree: true,
    },
    // Cognitive Science Resources
    {
      id: "cognitive-mit-course",
      title: "Introduction to Cognitive Science",
      type: "course",
      url: "https://ocw.mit.edu/courses/brain-and-cognitive-sciences/9-00sc-introduction-to-psychology-fall-2011/",
      difficulty: "intermediate",
      category: "psychology",
      topic: "cognitive-science",
      description: "MIT's exploration of mind and cognition",
      duration: "12 weeks",
      provider: "MIT",
      rating: 4.7,
      tags: ["cognitive-science", "mit", "neuroscience"],
      language: "English",
      isFree: true,
    },
  ],
  mathematics: [
    // Calculus Resources
    {
      id: "calculus-khan-academy",
      title: "Calculus Course",
      type: "course",
      url: "https://www.khanacademy.org/math/calculus-1",
      difficulty: "intermediate",
      category: "mathematics",
      topic: "calculus",
      description: "Comprehensive calculus with practice exercises",
      duration: "50 hours",
      provider: "Khan Academy",
      rating: 4.7,
      tags: ["calculus", "derivatives", "integrals"],
      language: "English",
      isFree: true,
    },
    {
      id: "calculus-mit-course",
      title: "Single Variable Calculus",
      type: "course",
      url: "https://ocw.mit.edu/courses/mathematics/18-01sc-single-variable-calculus-fall-2010/",
      difficulty: "advanced",
      category: "mathematics",
      topic: "calculus",
      description: "MIT's rigorous single variable calculus course",
      duration: "15 weeks",
      provider: "MIT OpenCourseWare",
      rating: 4.8,
      tags: ["calculus", "mit", "advanced"],
      prerequisites: ["pre-calculus"],
      language: "English",
      isFree: true,
    },
    // Statistics Resources
    {
      id: "statistics-khan-academy",
      title: "Statistics and Probability",
      type: "course",
      url: "https://www.khanacademy.org/math/statistics-probability",
      difficulty: "beginner",
      category: "mathematics",
      topic: "statistics",
      description: "Comprehensive statistics and probability course",
      duration: "30 hours",
      provider: "Khan Academy",
      rating: 4.6,
      tags: ["statistics", "probability", "data-analysis"],
      language: "English",
      isFree: true,
    },
    {
      id: "statistics-mit-course",
      title: "Introduction to Probability and Statistics",
      type: "course",
      url: "https://ocw.mit.edu/courses/mathematics/18-05-introduction-to-probability-and-statistics-spring-2014/",
      difficulty: "intermediate",
      category: "mathematics",
      topic: "statistics",
      description: "MIT's comprehensive statistics course",
      duration: "14 weeks",
      provider: "MIT OpenCourseWare",
      rating: 4.7,
      tags: ["statistics", "probability", "mit"],
      language: "English",
      isFree: true,
    },
  ],
}

export function getResourcesByCategory(category: string): LearningResource[] {
  return learningResourcesDatabase[category] || []
}

export function getResourcesByTopic(category: string, topic: string): LearningResource[] {
  const categoryResources = getResourcesByCategory(category)
  return categoryResources.filter((resource) => resource.topic === topic)
}

export function searchResources(query: string): LearningResource[] {
  const allResources = Object.values(learningResourcesDatabase).flat()
  return allResources.filter(
    (resource) =>
      resource.title.toLowerCase().includes(query.toLowerCase()) ||
      resource.description.toLowerCase().includes(query.toLowerCase()) ||
      resource.tags.some((tag) => tag.toLowerCase().includes(query.toLowerCase())),
  )
}
